spring:
  application:
    name: auth-service
  # Database settings
  datasource:
    url: jdbc:mysql://localhost:3306/auth_service?createDatabaseIfNotExist=true
    username: root
    password: 2002
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA/Hibernate settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

# Server settings
server:
  port: 8080

## JWT Configuration
jwt:
  secret-key: your-secure-secret-key-here
  expiration-seconds: 1800
  issuer: stranger-app

auth:
  jwt:
    use-db: true  # Toggle between true (secure) / false (fast)

# Swagger UI custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html

#    tags-sorter: alpha
#    operations-sorter: alpha
#  api-docs:
#    path: /v3/api-docs
#    enabled: true
#  packages-to-scan: com.suraj.authservice.controller
#  paths-to-match: /api/**
  
# Logging configuration
logging:
  level:
    root: INFO
    com.suraj.authservice: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springdoc: DEBUG